try4deploy fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,7 +4,7 @@ name: Deploy static content to Pages
 on:
   # Runs on pushes targeting the default branch
   push:
-    branches: ["gh-pages"]
+    branches: ["main", "gh-pages"]
 
 
  # Allows you to run this workflow manually from the Actions tab
@@ -37,7 +37,9 @@ jobs:
         with:
           node-version: 20
       - name: Install dependencies
-        run: npm ci
+        run: npm install --legacy-peer-deps
+      - name: Debug dependencies
+        run: ls -R node_modules/react-markdown || echo "react-markdown not found"
       - name: Fix permissions
         run: chmod +x node_modules/.bin/vite
       - name: Build
